### Capstone project name

- <b>Environmental Research Question / Intro & Background:</b>
	- Why do we care about this topic? Why is it important? 
    - Cite recent trends to convince a reader who's new to the topic
- <b>Data:</b>
	- Where did you get your data from?
    - What does it measure?
    - What caveats does a new audience need to know about your data?
    	- For e.g. if it only covers certain pollutant types, it might not measure XYZ "edge cases"
- <b>Exploratory Data Analysis:</b>
	- Give new audiences a "lay of the land" / What is the "shape" of your data?
    - Imagine you're standing at a viewpoint of a town
    	- What are the important landmarks? 
        - Is this a rural or urban town? 
        - Coastal, mountains, grassland?
        - Is it 70% agriculture or 20% agriculture? 
- <b>Final Analysis and Visualizations:</b>
	- What visualizations answer your initial Environmental Research Questions? 
- <b>Ethical Considerations / Limitations:</b>
	- What caveats should a new audience know about your capstone? 
    - We've formed some opinions about your capstone - what opinions should we NOT form? 
    - I.e. "Take my capstone with these pinches of salt"
- <b>Big picture takeaways / Future directions:</b>
	- Summarize your project in the 5 most important sentences
-  <b>Notes for reproducibility:</b>
	- Write a step-by-step summarizing what I did to produce this project

In [3]:
library(tidyverse)
#install.packages('readxl')
library(readxl)
cs20 <- read.csv('data/co-est2020-alldata.csv')
hpi <- read_excel('data/hpi_at_bdl_county.xlsx',skip=6)
head(cs20)
head(hpi)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

  SUMLEV REGION DIVISION STATE COUNTY STNAME  CTYNAME        CENSUS2010POP
1 40     3      6        1     0      Alabama Alabama        4779736
2 50     3      6        1     1      Alabama Autauga County 54571
3 50     3      6        1     3      Alabama Baldwin County 182265
4 50     3      6        1     5      Alabama Barbour County 27457
5 50     3      6        1     7      Alabama Bibb County    22915
6 50     3      6        1     9      Alabama Blount County  57322
  ESTIMATESBASE2010 POPESTIMATE2010 ⋯ RNETMIG2011 RNETMIG2012 RNETMIG2013
1 4780118           4785514         ⋯  0.6800098   1.282825    1.6143914
2   54582             54761         ⋯  6.2369306  -5.971016   -3.7733441
3  182263            183121         ⋯ 16.7054368  17.670696   22.9242875
4   27454             27325         ⋯  0.3292542  -6.860371   -8.0934255
5   22904             22858         ⋯ -4.9129271  -3.789130   -5.8006952
6   57322             57372         ⋯  0.3480289  -1.597971   -0.2777416
  RNETMIG2014 RNETMIG2015 RNETMIG2016 RNETMIG2017 RNETMIG2018 RNETMIG2019
1  0.6538283    0.7304192   0.8543837   1.197150   1.9660955   2.6778663
2  2.2066400   -1.5297064   4.9544032   0.993228  -0.0180211   3.4860110
3 20.3000883   17.9022731  21.4364985  22.476720  24.8463353  25.2425074
4 -5.0638567  -15.6779980 -18.3778392 -25.138734  -8.7901550  -6.2570644
5  1.4206122    1.2862022  -0.8417695  -3.235672  -7.2715917   0.2689799
6 -1.9971172   -1.3035430  -1.2171585   6.193186   0.2422753   0.9341752
  RNETMIG2020
1  3.091308
2  6.290545
3 26.401562
4  0.649799
5 -7.199262
6  1.192544

  State County  FIPS code Year Annual Change (%) HPI    HPI with 1990 base
1 AL    Autauga 01001     1986 .                 100.00 95.59
2 AL    Autauga 01001     1987 -1.94             98.06  93.74
3 AL    Autauga 01001     1988 2.57              100.58 96.14
4 AL    Autauga 01001     1989 4.32              104.92 100.29
5 AL    Autauga 01001     1990 -0.29             104.62 100.00
6 AL    Autauga 01001     1991 2.52              107.25 102.52
  HPI with 2000 base
1 70.96
2 69.59
3 71.38
4 74.46
5 74.24
6 76.11

In [4]:
?read_excel

read_excel               package:readxl                R Documentation

_R_e_a_d _x_l_s _a_n_d _x_l_s_x _f_i_l_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     Read xls and xlsx files

     ‘read_excel()’ calls ‘excel_format()’ to determine if ‘path’ is
     xls or xlsx, based on the file extension and the file itself, in
     that order. Use ‘read_xls()’ and ‘read_xlsx()’ directly if you
     know better and want to prevent such guessing.

_U_s_a_g_e:

     read_excel(
       path,
       sheet = NULL,
       range = NULL,
       col_names = TRUE,
       col_types = NULL,
       na = "",
       trim_ws = TRUE,
       skip = 0,
       n_max = Inf,
       guess_max = min(1000, n_max),
       progress = readxl_progress(),
       .name_repair = "unique"
     )

     read_xls(
       path,
       sheet = NULL,
       range = NULL,
       col_names = TRUE,
       col_types = NULL,
       na = "",
       trim_ws = TRUE,
       skip = 0,
       n_max = Inf,
       guess_max = min(1000, n_max),
       progress = readxl_progress(),
       .name_repair = "unique"
     )

     read_xlsx(
       path,
       sheet = NULL,
       range = NULL,
       col_names = TRUE,
       col_types = NULL,
       na = "",
       trim_ws = TRUE,
       skip = 0,
       n_max = Inf,
       guess_max = min(1000, n_max),
       progress = readxl_progress(),
       .name_repair = "unique"
     )

_A_r_g_u_m_e_n_t_s:

    path: Path to the xls/xlsx file.

   sheet: Sheet to read. Either a string (the name of a sheet), or an
          integer (the position of the sheet). Ignored if the sheet is
          specified via ‘range’. If neither argument specifies the
          sheet, defaults to the first sheet.

   range: A cell range to read from, as described in
          cell-specification. Includes typical Excel ranges like
          "B3:D87", possibly including the sheet name like
          "Budget!B2:G14", and more. Interpreted strictly, even if the
          range forces the inclusion of leading or trailing empty rows
          or columns. Takes precedence over ‘skip’, ‘n_max’ and
          ‘sheet’.

col_names: ‘TRUE’ to use the first row as column names, ‘FALSE’ to get
          default names, or a character vector giving a name for each
          column. If user provides ‘col_types’ as a vector, ‘col_names’
          can have one entry per column, i.e. have the same length as
          ‘col_types’, or one entry per unskipped column.

col_types: Either ‘NULL’ to guess all from the spreadsheet or a
          character vector containing one entry per column from these
          options: "skip", "guess", "logical", "numeric", "date",
          "text" or "list". If exactly one ‘col_type’ is specified, it
          will be recycled. The content of a cell in a skipped column
          is never read and that column will not appear in the data
          frame output. A list cell loads a column as a list of length
          1 vectors, which are typed using the type guessing logic from
          ‘col_types = NULL’, but on a cell-by-cell basis.

      na: Character vector of strings to interpret as missing values.
          By default, readxl treats blank cells as missing data.

 trim_ws: Should leading and trailing whitespace be trimmed?

    skip: Minimum number of rows to skip before reading anything, be it
          column names or data. Leading empty rows are automatically
          skipped, so this is a lower bound. Ignored if ‘range’ is
          given.

   n_max: Maximum number of data rows to read. Trailing empty rows are
          automatically skipped, so this is an upper bound on the
          number of rows in the returned tibble. Ignored if ‘range’ is
          given.

guess_max: Maximum number of data rows to use for guessing column
          types.

progress: Display a progress spinner? By default, the spinner appears
          only in an interactive session, outside the context of
          knitting a document, and when the call is likely to run for
          several seconds or more. See ‘readxl_progress()’ for more
          details.

.name_repair: Handling of column names. Passed along to
          ‘tibble::as_tibble()’. readxl's default is `.name_repair =
          "unique", which ensures column names are not empty and are
          unique.

_V_a_l_u_e:

     A tibble

_S_e_e _A_l_s_o:

     cell-specification for more details on targetting cells with the
     ‘range’ argument

_E_x_a_m_p_l_e_s:

     datasets <- readxl_example("datasets.xlsx")
     read_excel(datasets)

     # Specify sheet either by position or by name
     read_excel(datasets, 2)
     read_excel(datasets, "mtcars")

     # Skip rows and use default column names
     read_excel(datasets, skip = 10, col_names = FALSE)

     # Recycle a single column type
     read_excel(datasets, col_types = "text")

     # Specify some col_types and guess others
     read_excel(
       readxl_example("deaths.xlsx"),
       skip = 4, n_max = 10, col_names = TRUE,
       col_types = c("text", "text", "guess", "guess", "guess", "guess")
     )

     # Accomodate a column with disparate types via col_type = "list"
     df <- read_excel(readxl_example("clippy.xlsx"), col_types = c("text", "list"))
     df
     df$value
     sapply(df$value, class)

     # Limit the number of data rows read
     read_excel(datasets, n_max = 3)

     # Read from an Excel range using A1 or R1C1 notation
     read_excel(datasets, range = "C1:E7")
     read_excel(datasets, range = "R1C2:R2C5")

     # Specify the sheet as part of the range
     read_excel(datasets, range = "mtcars!B1:D5")

     # Read only specific rows or columns
     read_excel(datasets, range = cell_rows(102:151), col_names = FALSE)
     read_excel(datasets, range = cell_cols("B:D"))

     # Get a preview of column names
     names(read_excel(readxl_example("datasets.xlsx"), n_max = 0))

     # exploit full .name_repair flexibility from tibble

     # "universal" names are unique and syntactic
     read_excel(
       readxl_example("deaths.xlsx"),
       range = "arts!A5:F15",
       .name_repair = "universal"
     )

     # specify name repair as a built-in function
     read_excel(readxl_example("clippy.xlsx"), .name_repair = toupper)

     # specify name repair as a custom function
     my_custom_name_repair <- function(nms) tolower(gsub("[.]", "_", nms))
     read_excel(
       readxl_example("datasets.xlsx"),
       .name_repair = my_custom_name_repair
     )

     # specify name repair as an anonymous function
     read_excel(
       readxl_example("datasets.xlsx"),
       sheet = "chickwts",
       .name_repair = ~ substr(.x, start = 1, stop = 3)
     )